### ISSUE TITLE
Flex/Grid don't apply `align-content`/`items` when not given

### ISSUE THREAD

**Issue by aarvinr** [project-w3bx/style#4]
**Describe the bug**
When using the `flex` or `grid` properties, if the `align` property is not specified, it remains unset.

**To Reproduce**
1. Add `flex` to `.style` without the `align` property:
    ```css
    :root {
      flex: row center;
    }
    ```
2. Compile the `.style` and view the result:
    ```css
    :root {
      display: flex;
      flex-direction: row;
      justify-content: center;
    }
    ```

**Expected behavior**
The compiled `.style` should result in both `justify` and `align` set to `center`:

```css
:root {
  display: flex;
  flex-direction: row;
  justify-content: center;
  align-items: center;
}
```

**Screenshots**
N/A

**Additional context**
N/A
